name: CD Pipeline

on: 
  workflow_run: 
    workflows: ["Scan CI"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: build
    env:
      CONTAINER_NAME: shoeshop_fe
      IMAGE_OLD_TAG: latest
      IMAGE_NEW_TAG: latest
      IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPO }}

    steps:
      - name: Delete old docker container
        run: docker rm -f ${{ env.CONTAINER_NAME }} || true
        
      - name: Delete old image
        run: docker rmi ${{ env.IMAGE_NAME }}:${{ env.IMAGE_OLD_TAG }} || true

      - name: Docker pull
        run: docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_NEW_TAG }} 
        
      - name: Run container
        run: docker run --name ${{ env.CONTAINER_NAME }} -dp 3000:3000 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_NEW_TAG }} 